import{cleanup,fireEvent,render,screen,waitFor}from"@testing-library/react";import{afterEach,describe,expect,it,vi}from"vitest";import App from"./App";
afterEach(()=>{cleanup();vi.restoreAllMocks()});
const dashboard={counts:{pendingApprovals:1,activeSchedules:2,recentErrors:0},recentRuns:[],recentTools:[],recentScheduleExecutions:[]};
function json(value:unknown,status=200){return Promise.resolve(Response.json(value,{status}))}
describe("Jarvis Admin",()=>{
  it("loads Dashboard and shows summary counts",async()=>{vi.spyOn(globalThis,"fetch").mockImplementation(()=>json(dashboard));render(<App/>);expect(await screen.findByText("Pending approvals")).toBeInTheDocument();expect(screen.getByText("2")).toBeInTheDocument()});
  it("supports Memory list, create, update and confirmed delete",async()=>{const fetchMock=vi.spyOn(globalThis,"fetch").mockImplementation((input,init)=>{const url=String(input);if(url.endsWith("/admin/dashboard"))return json(dashboard);if(url.endsWith("/memories")&&init?.method==="POST")return json({id:"profile:language",type:"profile",key:"language",value:"ko",source:"user",createdAt:"",updatedAt:""});if(url.includes("/memories/profile%3Atimezone")&&init?.method==="PATCH")return json({id:"profile:timezone"});if(url.includes("/memories/profile%3Atimezone")&&init?.method==="DELETE")return json({deleted:true});return json({profile:[{id:"profile:timezone",type:"profile",key:"timezone",value:"Asia/Seoul",source:"user",createdAt:"",updatedAt:""}],longTerm:[]})});vi.spyOn(window,"prompt").mockReturnValue("Asia/Tokyo");vi.spyOn(window,"confirm").mockReturnValue(true);render(<App/>);fireEvent.click(screen.getByRole("button",{name:"Memory"}));expect(await screen.findByText("Asia/Seoul")).toBeInTheDocument();fireEvent.change(screen.getByLabelText("Memory key"),{target:{value:"language"}});fireEvent.change(screen.getByLabelText("Memory value"),{target:{value:"ko"}});fireEvent.click(screen.getByRole("button",{name:"추가"}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith("/api/memories",expect.objectContaining({method:"POST"})));fireEvent.click(screen.getByRole("button",{name:"수정"}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith("/api/memories/profile%3Atimezone",expect.objectContaining({method:"PATCH"})));fireEvent.click(screen.getByRole("button",{name:"삭제"}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith("/api/memories/profile%3Atimezone",expect.objectContaining({method:"DELETE"})))});
  it("approves and rejects pending Approvals with immediate refresh",async()=>{const pending=[{approvalId:"a1",conversationId:"c1",toolName:"gmail.send",toolArguments:{to:"test@example.com"},status:"PENDING",requestedAt:"2026-08-12",expiresAt:null,resultSummary:null,error:null},{approvalId:"a2",conversationId:"c2",toolName:"calendar.delete",toolArguments:{eventId:"e"},status:"PENDING",requestedAt:"2026-08-12",expiresAt:null,resultSummary:null,error:null}];const fetchMock=vi.spyOn(globalThis,"fetch").mockImplementation((input,init)=>String(input).includes("/approvals/")?json({approval:{...pending[0],status:"REJECTED"}}):String(input).endsWith("/approvals")?json({approvals:pending}):json(dashboard));render(<App/>);fireEvent.click(screen.getByRole("button",{name:"Approvals"}));expect(await screen.findByText("gmail.send")).toBeInTheDocument();fireEvent.click(screen.getAllByRole("button",{name:"승인"})[0]!);await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith("/api/approvals/a1/approve",expect.objectContaining({method:"POST"})));fireEvent.click(screen.getAllByRole("button",{name:"거부"})[1]!);await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith("/api/approvals/a2/reject",expect.objectContaining({method:"POST"})))});
  it("creates, disables, runs and deletes Schedules",async()=>{const schedule={id:"s1",title:"Daily",instruction:"오늘 일정",scheduleType:"recurring",scheduleRule:{frequency:"daily",hour:8,minute:0},timezone:"Asia/Seoul",enabled:true,status:"scheduled",lastRunAt:null,nextRunAt:"2026-08-13T00:00:00Z",lastResult:null};const fetchMock=vi.spyOn(globalThis,"fetch").mockImplementation((input,init)=>{const u=String(input);if(u.endsWith("/schedules")&&init?.method==="POST")return json(schedule,201);if(u.endsWith("/schedules"))return json({schedules:[schedule]});if(u.includes("/schedules/s1"))return json(init?.method==="DELETE"?{deleted:true}:schedule);return json(dashboard)});vi.spyOn(window,"confirm").mockReturnValue(true);render(<App/>);fireEvent.click(screen.getByRole("button",{name:"Schedules"}));expect(await screen.findByText("Daily")).toBeInTheDocument();fireEvent.change(screen.getByLabelText("Schedule title"),{target:{value:"Once"}});fireEvent.change(screen.getByLabelText("Instruction"),{target:{value:"안녕"}});fireEvent.change(screen.getByLabelText("Run at"),{target:{value:"2027-01-01T10:00"}});fireEvent.click(screen.getByRole("button",{name:"생성"}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith("/api/schedules",expect.objectContaining({method:"POST"})));fireEvent.click(screen.getByRole("button",{name:"비활성화"}));fireEvent.click(screen.getByRole("button",{name:"실행"}));fireEvent.click(screen.getByRole("button",{name:"삭제"}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith("/api/schedules/s1/run",expect.objectContaining({method:"POST"})))});
  it("shows History and loads an Agent execution detail",async()=>{const run={id:"r1",request:"안녕",response:"반갑습니다",model:"test",status:"completed",error:null,executionTimeMs:4,createdAt:"2026-08-12",triggerType:"manual"};vi.spyOn(globalThis,"fetch").mockImplementation(input=>String(input).endsWith("/history/r1")?json(run):String(input).endsWith("/history")?json({runs:[run],scheduleExecutions:[]}):json(dashboard));render(<App/>);fireEvent.click(screen.getByRole("button",{name:"History"}));expect(await screen.findByText("안녕")).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"상세"}));expect(await screen.findByText("반갑습니다")).toBeInTheDocument()});
  it("shows an API connection error in the UI",async()=>{vi.spyOn(globalThis,"fetch").mockRejectedValue(new TypeError("Failed to fetch"));render(<App/>);expect(await screen.findByRole("alert")).toHaveTextContent("Jarvis API에 연결할 수 없습니다.")});
});
