import type{SqlExecutor}from"../storage/sql";

export type ProviderHealthLevel="healthy"|"degraded"|"unavailable"|"unknown";
export interface ProviderHealthStatus{target:string;status:ProviderHealthLevel;checkedAt:string;expiresAt:string;latencyMs?:number;reason?:string;consecutiveFailures:number}
interface Row{target:string;status:ProviderHealthLevel;latency_ms:number|null;reason:string|null;consecutive_failures:number;checked_at:string;expires_at:string}
export class ProviderHealthRepository{
  constructor(private readonly db:SqlExecutor,private readonly ttlMs=60_000){}
  get(target:string):ProviderHealthStatus|undefined{const[row]=this.db.sql<Row>`SELECT target,status,latency_ms,reason,consecutive_failures,checked_at,expires_at FROM provider_health_cache WHERE target=${target}`;return row?map(row):undefined;}
  set(target:string,status:ProviderHealthLevel,input:{latencyMs?:number;reason?:string}={}):ProviderHealthStatus{const previous=this.get(target),checkedAt=new Date().toISOString(),expiresAt=new Date(Date.now()+this.ttlMs).toISOString(),failures=status==="healthy"?0:(previous?.consecutiveFailures??0)+1;this.db.sql`INSERT INTO provider_health_cache (target,status,latency_ms,reason,consecutive_failures,checked_at,expires_at) VALUES (${target},${status},${input.latencyMs??null},${input.reason??null},${failures},${checkedAt},${expiresAt}) ON CONFLICT(target) DO UPDATE SET status=excluded.status,latency_ms=excluded.latency_ms,reason=excluded.reason,consecutive_failures=excluded.consecutive_failures,checked_at=excluded.checked_at,expires_at=excluded.expires_at`;return{target,status,checkedAt,expiresAt,consecutiveFailures:failures,...input};}
  list():ProviderHealthStatus[]{return this.db.sql<Row>`SELECT target,status,latency_ms,reason,consecutive_failures,checked_at,expires_at FROM provider_health_cache ORDER BY target`.map(map);}
}
function map(row:Row):ProviderHealthStatus{return{target:row.target,status:row.status,checkedAt:row.checked_at,expiresAt:row.expires_at,consecutiveFailures:row.consecutive_failures,...(row.latency_ms!==null?{latencyMs:row.latency_ms}:{}),...(row.reason?{reason:row.reason}:{})}}

export type FailureType="timeout"|"network"|"rate-limit"|"provider-unavailable"|"server-error"|"authentication"|"permission"|"invalid-input"|"not-found"|"unknown";
export interface FailureClassification{type:FailureType;fallbackEligible:boolean;retryEligible:boolean;uncertainSideEffect:boolean}
export function classifyProviderFailure(error:unknown):FailureClassification{const text=(error instanceof Error?`${error.name} ${error.message} ${(error.cause as Error|undefined)?.message??""}`:String(error)).toLowerCase();if(/abort|timeout|timed out/.test(text))return{type:"timeout",fallbackEligible:true,retryEligible:true,uncertainSideEffect:true};if(/429|rate.?limit/.test(text))return{type:"rate-limit",fallbackEligible:true,retryEligible:true,uncertainSideEffect:false};if(/401|unauth|oauth|token.*expired/.test(text))return{type:"authentication",fallbackEligible:false,retryEligible:false,uncertainSideEffect:false};if(/403|permission|forbidden/.test(text))return{type:"permission",fallbackEligible:false,retryEligible:false,uncertainSideEffect:false};if(/400|invalid|validation/.test(text))return{type:"invalid-input",fallbackEligible:false,retryEligible:false,uncertainSideEffect:false};if(/404|not found/.test(text))return{type:"not-found",fallbackEligible:false,retryEligible:false,uncertainSideEffect:false};if(/5\d\d|server error/.test(text))return{type:"server-error",fallbackEligible:true,retryEligible:true,uncertainSideEffect:true};if(/network|connect|fetch failed|unavailable|disconnected/.test(text))return{type:"network",fallbackEligible:true,retryEligible:true,uncertainSideEffect:true};return{type:"unknown",fallbackEligible:false,retryEligible:false,uncertainSideEffect:true};}
