import {describe,expect,it,vi} from "vitest";
import {GenericMcpClient} from "../src/mcp/generic-mcp-client";
import {adaptMcpTools} from "../src/mcp/mcp-tool-adapter";
import type {StoredMcpServer} from "../src/mcp/types";

const server:StoredMcpServer={id:"docs",name:"Cloudflare Docs",endpoint:"https://docs.mcp.cloudflare.com/mcp",transport:"streamable-http",enabled:true,authType:"none",service:"search",providerId:"cloudflare-docs-mcp",capabilityMapping:{search:"search"},createdAt:"now",updatedAt:"now"};

function fixture(){const state={servers:{} as Record<string,{state:string;error:null;auth_url:null}>,tools:[] as Array<{serverId:string;name:string;description:string;inputSchema:Record<string,unknown>}>};const callTool=vi.fn().mockResolvedValue({content:[{type:"text",text:"ok"}]});const host={addMcpServer:vi.fn(async()=>{state.servers.docs={state:"ready",error:null,auth_url:null};state.tools=[{serverId:"docs",name:"search",description:"Search docs",inputSchema:{type:"object"}}];return{id:"docs",state:"ready"}}),removeMcpServer:vi.fn(async(id:string)=>{delete state.servers[id]}),getMcpServers:()=>state,mcp:{closeConnection:vi.fn(async(id:string)=>{state.servers[id]!.state="disconnected"}),discoverIfConnected:vi.fn(async()=>({success:true,state:"ready"})),callTool}};return{client:new GenericMcpClient(host),host,state,callTool};}

describe("Generic MCP client",()=>{
  it("connects, discovers, invokes and disconnects without protocol-specific code",async()=>{const{client,host,callTool}=fixture();expect(await client.connect(server)).toMatchObject({state:"ready",connected:true});expect(await client.discover("docs")).toEqual([{serverId:"docs",toolName:"search",description:"Search docs",inputSchema:{type:"object"}}]);await client.callTool("docs","search",{query:"Agents"});expect(callTool).toHaveBeenCalledWith({serverId:"docs",name:"search",arguments:{query:"Agents"}});await client.disconnect("docs");expect(client.status("docs").connected).toBe(false);expect(host.addMcpServer).toHaveBeenCalledWith("Cloudflare Docs",server.endpoint,expect.objectContaining({id:"docs"}));});
  it("keeps credentials out of registry metadata and resolves headers only at connect time",async()=>{const{host}=fixture();const client=new GenericMcpClient(host,reference=>reference==="MCP_TOKEN"?"secret":undefined);await client.connect({...server,authType:"bearer",credentialReference:"MCP_TOKEN"});expect(host.addMcpServer).toHaveBeenCalledWith(expect.anything(),expect.anything(),expect.objectContaining({transport:expect.objectContaining({headers:{authorization:"Bearer secret"}})}));expect(JSON.stringify(server)).not.toContain("secret");});
  it("adapts discovered tools with conservative approval policy",async()=>{const{client}=fixture();const[adapted]=adaptMcpTools(client,[{serverId:"docs",toolName:"search/docs",description:"Search",inputSchema:{type:"object"}}]);expect(adapted?.tool).toMatchObject({name:"mcp__docs__search_docs",policy:"APPROVAL_REQUIRED",requiresApproval:true});});
});
