import{describe,expect,it}from"vitest";
import type{Env}from"../src/env";
import{ModelConfigurationRepository}from"../src/llm/model-configuration-repository";
import{ModelConfigurationService}from"../src/llm/model-configuration-service";
import{createModelRegistry}from"../src/llm/model-registry";
import{RuntimeConfigurationHistoryRepository}from"../src/runtime/runtime-configuration-history-repository";
import{RuntimeConfigurationManager}from"../src/runtime/runtime-configuration-manager";
import{parseRuntimeConfigurationIntent}from"../src/runtime/runtime-configuration-tools";
import type{SqlExecutor}from"../src/storage/sql";
import{ToolProviderConfigurationRepository}from"../src/tools/tool-provider-configuration-repository";
import{ToolProviderConfigurationService}from"../src/tools/tool-provider-configuration-service";
import{createToolProviderRegistry}from"../src/tools/tool-provider-registry";

function fixture(){const model=new Map<string,unknown>();const providers=new Map<string,{service:string;provider_id:string;updated_at:string}>();const history:Array<Record<string,unknown>>=[];const sql:SqlExecutor["sql"]=((strings:TemplateStringsArray,...values:Array<string|number|boolean|null>)=>{const statement=strings.join("?");if(statement.includes("SELECT provider, model_id")){const row=model.get("active");return row?[row]:[];}if(statement.includes("INSERT INTO model_configuration")){model.set("active",{provider:values[0],model_id:values[1],updated_at:values[2]});return[];}if(statement.includes("SELECT service, provider_id")){const row=providers.get(String(values[0]));return row?[row]:[];}if(statement.includes("INSERT INTO tool_provider_configuration")){providers.set(String(values[0]),{service:String(values[0]),provider_id:String(values[1]),updated_at:String(values[2])});return[];}if(statement.includes("INSERT INTO runtime_configuration_history")){history.push({id:values[0],change_type:values[1],target:values[2],previous_value_json:values[3],new_value_json:values[4],source:values[5],created_at:values[6]});return[];}if(statement.includes("SELECT id,change_type"))return[...history].reverse();return[];})as SqlExecutor["sql"];const db={sql};const env={AI:{run:async()=>({})},OPENAI_API_KEY:"openai-secret",GOOGLE_CLIENT_ID:"id",GOOGLE_CLIENT_SECRET:"secret",SEARCH_API_KEY:"brave"}as unknown as Env;const models=new ModelConfigurationService(new ModelConfigurationRepository(db),createModelRegistry(env));const toolRegistry=createToolProviderRegistry(env,{googleConnected:true},[{service:"search",providerId:"docs-mcp",displayName:"Docs MCP",enabled:true,requiresAuth:false,capabilities:["search"],type:"mcp",mcpServerId:"docs"}]);const tools=new ToolProviderConfigurationService(new ToolProviderConfigurationRepository(db),toolRegistry);const mcp={list:()=>[{id:"docs",name:"Docs",enabled:true,authType:"none",service:"search",providerId:"docs-mcp",capabilityMapping:{search:"search"},connection:{state:"ready",connected:true}}]}as never;const historyRepo=new RuntimeConfigurationHistoryRepository(db);return{manager:new RuntimeConfigurationManager(models,tools,mcp,historyRepo),models,tools,historyRepo,providers,model};}

describe("Runtime Configuration Manager",()=>{
  it("returns one secret-free runtime snapshot",()=>{const{manager}=fixture();const snapshot=manager.getConfiguration();expect(snapshot.model.active).toMatchObject({provider:"workers-ai",isDefault:true});expect(snapshot.tools["search"]!.active.providerId).toBe("brave-api");expect(snapshot.mcp.servers[0]).toMatchObject({id:"docs",connection:{state:"ready"}});expect(JSON.stringify(snapshot)).not.toContain("openai-secret");});
  it("validates a composite plan before applying all changes and records history",()=>{const{manager,models,tools}=fixture();const result=manager.applyChange([{kind:"model.set",provider:"openai"},{kind:"tool.set",service:"search",providerId:"mcp"}]);expect(result.plan).toHaveLength(2);expect(models.getActive().provider).toBe("openai");expect(tools.getActive("search").providerId).toBe("docs-mcp");expect(manager.getHistory()).toHaveLength(2);});
  it("rejects the whole composite plan when one validation fails",()=>{const{manager,models,tools}=fixture();expect(()=>manager.applyChange([{kind:"tool.set",service:"search",providerId:"mcp"},{kind:"model.set",provider:"openai",model:"not-registered"}])).toThrow("Unknown model");expect(models.getActive().provider).toBe("workers-ai");expect(tools.getActive("search").providerId).toBe("brave-api");expect(manager.getHistory()).toHaveLength(0);});
  it("resets active selections without deleting MCP registrations",()=>{const{manager}=fixture();manager.applyChange([{kind:"model.set",provider:"openai"},{kind:"tool.set",service:"search",providerId:"mcp"}]);manager.resetAll();expect(manager.getConfiguration()).toMatchObject({model:{active:{provider:"workers-ai"}},tools:{search:{active:{providerId:"brave-api"}}},mcp:{servers:[{id:"docs"}]}});});
  it("parses explicit composite mutations but ignores opinions and ordinary Gmail requests",()=>{expect(parseRuntimeConfigurationIntent("모델은 OpenAI로 바꾸고 Search는 MCP로 사용해.")).toMatchObject({toolName:"runtime.apply_changes",arguments:{changes:[{kind:"model.set",provider:"openai"},{kind:"tool.set",service:"search",providerId:"mcp"}]}});expect(parseRuntimeConfigurationIntent("Gmail MCP가 좋은 것 같아.")).toBeNull();expect(parseRuntimeConfigurationIntent("오늘 받은 Gmail 보여줘.")).toBeNull();expect(parseRuntimeConfigurationIntent("현재 Jarvis 설정 알려줘.")?.toolName).toBe("runtime.get_configuration");expect(parseRuntimeConfigurationIntent("최근 설정 변경 내역 보여줘.")?.toolName).toBe("runtime.list_history");});
  it("redacts sensitive keys from change history",()=>{const{historyRepo}=fixture();historyRepo.record({changeType:"test",target:"mcp.test",previousValue:{accessToken:"secret",id:"ok"},newValue:{authorization:"Bearer secret",authUrl:"https://login.test?state=sensitive",enabled:true},source:"user-command"});const serialized=JSON.stringify(historyRepo.list());expect(serialized).not.toContain("secret");expect(serialized).not.toContain("authorization");expect(serialized).not.toContain("authUrl");expect(serialized).not.toContain("sensitive");});
});
