export interface Memory{ id:string;type:"profile"|"long_term";key?:string;value?:string;content?:string;category?:string;source:string;createdAt:string;updatedAt:string }
export interface Approval{approvalId:string;conversationId:string;toolName:string;toolArguments:Record<string,unknown>;status:string;requestedAt:string;expiresAt:string|null;resultSummary:string|null;error:string|null}
export interface Schedule{id:string;title:string;instruction:string;scheduleType:"one_time"|"recurring";scheduleRule:Record<string,unknown>;timezone:string;enabled:boolean;status:string;lastRunAt:string|null;nextRunAt:string|null;lastResult:string|null}
export interface Run{id:string;request:string;response:string|null;model:string|null;status:string;error:string|null;executionTimeMs:number|null;createdAt:string;triggerType:"manual";toolExecutions?:Array<{toolName:string;success:boolean;resultSummary:string;executionTimeMs:number}>;tokenUsage?:number|null}
export interface ScheduleExecution{id:string;schedule_id:string;scheduleTitle?:string|null;trigger_type:"manual"|"scheduled";started_at:string;completed_at:string|null;success:number|null;tool_calls_json:string|null;response:string|null;error_message:string|null}
export interface ToolStatus{name:string;description:string;enabled:boolean;policy:string;requiresApproval:boolean;connection:string;permission:string;provider?:{service:"gmail"|"calendar"|"search"|"scheduler";implementation:"google-api"|"brave-api"|"serpapi"|"cloudflare-agents"|"unavailable";fallbackImplementation?:"google-api"|"brave-api"|"serpapi"|"cloudflare-agents"|"unavailable"};latestExecution:{success:boolean;createdAt:string;resultSummary:string}|null}
export interface Settings{language:string;timezone:string;responseTone:"friendly"|"professional"|"warm"|"direct";speechStyle:"polite"|"casual";responseDetail:"concise"|"balanced"|"detailed";customInstructions:string;llmProvider:string;llmModel:string;systemTimezone:string;secretsManagedBy:string}
export interface DashboardData{counts:{pendingApprovals:number;activeSchedules:number;recentErrors:number};recentRuns:Run[];recentTools:Array<{id:string;toolName:string;success:boolean;createdAt:string;resultSummary:string}>;recentScheduleExecutions:ScheduleExecution[]}
export type CapabilityGapStatus="unresolved"|"reviewed"|"ignored";
export interface CapabilityGap{id:string;createdAt:string;updatedAt:string;requestText:string;requestedCapability:string;service:string|null;label:"code-required";reason:string;status:CapabilityGapStatus}
export interface CapabilityGapSummary{service:string|null;requestedCapability:string;count:number;latestAt:string}
